export const questions = [
  {
    question: "What is the capital of France?",
    option1: "Berlin",
    option2: "Madrid",
    option3: "Paris",
    option4: "Rome",
    correctAnswer: "Paris",
  },
  {
    question: "Which planet is known as the Red Planet?",
    option1: "Earth",
    option2: "Mars",
    option3: "Jupiter",
    option4: "Saturn",
    correctAnswer: "Mars",
  },
  {
    question: "What is the largest ocean on Earth?",
    option1: "Atlantic Ocean",
    option2: "Indian Ocean",
    option3: "Arctic Ocean",
    option4: "Pacific Ocean",
    correctAnswer: "Pacific Ocean",
  },
  {
    question: "Who wrote 'To Kill a Mockingbird'?",
    option1: "Harper Lee",
    option2: "Mark Twain",
    option3: "Ernest Hemingway",
    option4: "F. Scott Fitzgerald",
    correctAnswer: "Harper Lee",
  },
  {
    question: "What is the smallest prime number?",
    option1: "0",
    option2: "1",
    option3: "2",
    option4: "3",
    correctAnswer: "2",
  },
  {
    question: "Which element has the chemical symbol 'O'?",
    option1: "Oxygen",
    option2: "Gold",
    option3: "Osmium",
    option4: "Oganesson",
    correctAnswer: "Oxygen",
  },
  {
    question: "What is the hardest natural substance on Earth?",
    option1: "Gold",
    option2: "Iron",
    option3: "Diamond",
    option4: "Platinum",
    correctAnswer: "Diamond",
  },
  {
    question: "Who painted the Mona Lisa?",
    option1: "Vincent van Gogh",
    option2: "Pablo Picasso",
    option3: "Leonardo da Vinci",
    option4: "Claude Monet",
    correctAnswer: "Leonardo da Vinci",
  },
  {
    question: "What is the largest mammal in the world?",
    option1: "Elephant",
    option2: "Blue Whale",
    option3: "Giraffe",
    option4: "Hippopotamus",
    correctAnswer: "Blue Whale",
  },
  {
    question: "Which country is known as the Land of the Rising Sun?",
    option1: "China",
    option2: "South Korea",
    option3: "Japan",
    option4: "Thailand",
    correctAnswer: "Japan",
  },
];
